food/urls.py
from django.urls import path
from food import views

app_name = 'food'
urlpatterns = [
    # index page
    # path('', views.index, name='index'),
    path('', views.IndexClassView.as_view(), name='index'),
    # path('item/', views.item, name='item'),
    # details page
    # path('<int:item_id>/', views.detail, name='detail'),
    path('<int:pk>/', views.FoodDetail.as_view(), name='detail'),
    # add items
    # path('add/', views.create_item, name='create_item'),
    path('add/', views.CreateItem.as_view(), name='create_item'),
    # update item
    path('update/<int:item_id>/', views.update_item, name='update_item'),
    # delete item
    path('delete/<int:item_id>/', views.delete_item, name='delete_item'),
    # Unauthorized page
    path('unauthorized/', views.unauthorized, name='unauthorized')
]

foodiee/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.profile, name='profile')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.

class Item(models.Model):

    def __str__(self):
        return self.item_name

    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.FloatField()
    item_image = models.CharField(max_length=500, default='https://www.dirtyapronrecipes.com/wp-content/uploads/2015/10/food-placeholder.png')
    item_created_by = models.ForeignKey(User, on_delete= models.CASCADE, default=1)

    def get_absolute_url(self):
        return reverse('food:detail', kwargs={'pk': self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.png', upload_to='profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name', 'item_desc', 'item_price', 'item_image']

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegistrationForm(UserCreationForm):

    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from food.models import Item
from .forms import ItemForm

from django.contrib.auth.decorators import login_required
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.utils.decorators import method_decorator

# Create your views here.

def index(request):

    item_list = Item.objects.all()
    return render(request, 'food/index.html', {
        'item_list': item_list
    })

# class based view

class IndexClassView(ListView):

    model = Item
    template_name = 'food/index.html'
    context_object_name = 'item_list'


# def item(request):
#     return HttpResponse('<h1>This is an Item.</h1>')

@login_required
def detail(request, item_id):
    item = Item.objects.get(pk=item_id)
    return render(request, 'food/details.html', {
        'object': item
    })

@method_decorator(login_required, name='dispatch')
class FoodDetail(DetailView):

    model = Item
    template_name = 'food/details.html'

@login_required
def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid():

        # updating the item_created_by field before saving in db
        form.instance.item_created_by = request.user
        form.save()
        return redirect(form.instance.get_absolute_url())

    return render(request, 'food/item-form.html', {
        'form': form
    })

@method_decorator(login_required, name='dispatch')
class CreateItem(CreateView):

    model = Item
    fields = ['item_name', 'item_desc', 'item_price', 'item_image']
    template_name = 'food/item-form.html'

    def form_valid(self, form):
        form.instance.item_created_by = self.request.user
        return super().form_valid(form)



@login_required
def update_item(request, item_id):
    item = Item.objects.get(pk=item_id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    if item.item_created_by == request.user:
        return render(request, 'food/item-form.html', {
            'form': form
        })
    else:
        return redirect('food:unauthorized')

@login_required
def delete_item(request, item_id):
    item = Item.objects.get(pk=item_id)

    if request.method == 'POST':
        item.delete()
        return redirect('food:index')

    if item.item_created_by == request.user:
        return render(request, 'food/item-delete.html', {
        'item': item
        })
    else:
        return redirect('food:unauthorized')


def unauthorized(request):

    return render(request, 'food/unauthorized.html')

users/views.py
from django.shortcuts import render, redirect
# from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import RegistrationForm
from django.contrib.auth.decorators import login_required

# Create your views here.

def register(request):

    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            messages.success(request, f'Welcome {username}, your account is created successfully.')
            return redirect('login')
    else:
        form = RegistrationForm()
    return render(request, 'users/register.html', {
        'form': form
    })

@login_required
def profile(request):

    return render(request, 'users/profile.html')

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
</head>
<body>
    <nav class="navbar navbar-dark bg-dark" style="margin-bottom: 1rem;">
        <a href="{% url 'food:index' %}" class="navbar-brand"> Foodiee</a>
        <div class="navbar">
            <a class="nav-item nav-link" href="{% url 'food:create_item'%}">Add item</a>
            {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
            {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
            {% endif %}
        </div>
    </nav>

    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">{{message}}</div>
        {% endfor %}
    {% endif %}

    {% block body %}
    {% endblock %}
</body>
</html>

food/templates/food/card.html
{% extends 'food/base.html' %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4 justify-content-center">
                <div class="card">
                    <div class="card-header bg-info text-white text-center">
                        <div class="card-title">
                            {% block cardtitle %}
                            {% endblock %}
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            <div>{{ form.non_field_errors }}</div>
                            <table>
                                {% for field in form %}
                                    {% for error in field.errors %}
                                        <tr>
                                            <td class="alert-danger" colspan="2">{{ error }}</td>
                                        </tr>
                                    {% endfor %}
                                    <tr>
                                        <td>{{ field.label_tag }}</td>
                                        <td>{{ field }}</td>
                                    </tr>
                                {% endfor %}
                            </table>
                            <div align="center" style="margin-top: 10px;">
                                <button class="btn btn-info center text-white" type="submit">
                                    {% block cardbutton %}
                                    {% endblock %}
                                </button>
                            </div>
                            
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

food/templates/food/details.html
{% extends 'food/base.html'%}

    {% block body %}
        <div class="container" >
            <div class="row">
                <div class="col-md-6">
                    <img class="card" height="300px" src="{{ item.item_image }}">
                </div>
                <div class="col-md-6">
                    <h1>{{ object.item_name }}</h1>
                    <h2>{{ object.item_desc }}</h2>
                    <h3>${{ object.item_price }}</h3>
                    <a class="btn btn-success" href="{% url 'food:update_item' object.id %}">Update</a>
                    <a class="btn btn-danger" href="{% url 'food:delete_item' object.id %}">Delete</a>
                </div>
            </div>
        </div>
    {% endblock %}

food/templates/food/index.html
{% extends 'food/base.html'%}

    {% block body %}

        {% for item in item_list %}
            <div class="row">
                <div class="col-md-3 offset-md-2">
                    <img class="card" width="200px" src="{{ item.item_image }}" />
                </div>
                <div class="col-md-4">
                    <h3>{{ item.item_name }}</h3>
                    <h5>{{ item.item_desc }}</h5>
                    <h6>${{ item.item_price }}</h6>
                    <h6>Added By: {{ item.item_created_by|capfirst }}</h6>
                </div>
                <div class="col-md-2">
                    <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>

                </div>
            </div>
        {% endfor %}
    {% endblock %}

food/templates/food/item-delete.html
{% extends 'food/base.html' %}

{% block body %}
    <form method="POST">
        {% csrf_token %}
        <h2>Are you sure you want to delete {{ item.item_name }} ?</h2>
        <input type="submit" class="btn btn-danger" value="Delete"/>
    </form>
{% endblock %}

food/templates/food/item-form.html
{% extends 'food/card.html' %}

{% block cardtitle%}
    Add a new Item
{% endblock%}

{% block cardbutton%}
    Add
{% endblock%}

food/templates/food/unauthorized.html
{% extends 'food/base.html' %}

{% block body %}
    <h2>You are not authorized to perform this operation.</h2>
{% endblock %}

users/templates/users/login.html
{% extends 'food/card.html' %}

{% block cardtitle%}
    Login
{% endblock%}

{% block cardbutton%}
    Login
{% endblock%}

users/templates/users/logout.html
{% extends 'food/base.html' %}

{% block body %}
    <h5>You have been logged out. Click <a href="{% url 'login' %}">here</a> to login.</h5>
{% endblock %}

users/templates/users/profile.html
{% extends 'food/base.html' %}

{% block body %}
    <h1>{{ user.username }}</h1>
    <img src="{{ user.profile.image.url }}" alt="Profile Picture not available" width="300px">
{% endblock %}

users/templates/users/register.html
{% extends 'food/card.html' %}

{% block cardtitle%}
    Register
{% endblock%}

{% block cardbutton%}
    Register
{% endblock%}